#!/usr/bin/env bash
# Wires only the managed keycaps block in the user's Hyprland Lua config.
set -euo pipefail

case "${1:-}" in
  "") mode=install ;;
  --uninstall|uninstall|-u) mode=uninstall ;;
  *) echo "usage: $0 [--uninstall]" >&2; exit 1 ;;
esac
[[ $# -le 1 ]] || { echo "usage: $0 [--uninstall]" >&2; exit 1; }

# The override also allows tests to exercise real file edits in a temp directory.
HYPRLAND_LUA="${KEYCAPS_HYPRLAND_CONFIG:-$HOME/.config/hypr/hyprland.lua}"
if [[ ! -f "$HYPRLAND_LUA" ]]; then
  echo "hyprland.lua not found at $HYPRLAND_LUA" >&2
  exit 1
fi

BEGIN_MARKER='-- BEGIN omarchy-keycaps bridge'
END_MARKER='-- END omarchy-keycaps bridge'
LINE='dofile(os.getenv("HOME") .. "/.config/omarchy/plugins/omarchy-keycaps/hypr/keys.lua")'
TEMP_CONFIG=$(mktemp "${HYPRLAND_LUA}.tmp.XXXXXX")
trap 'rm -f -- "$TEMP_CONFIG"' EXIT
FINAL_NEWLINE=0
[[ -z "$(tail -c 1 -- "$HYPRLAND_LUA")" ]] && FINAL_NEWLINE=1

# Match whole owned lines, never arbitrary occurrences of the plugin name.
# Also migrate the exact loader syntax generated by the two previous installers.
# Validate marker pairs before replacing anything in the original file.
awk -v BINMODE=3 -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v loader="$LINE" -v final_newline="$FINAL_NEWLINE" '
  function legacy(line) {
    return line ~ /^dofile\(\(os.getenv\("HOME"\) or "[^"]*"\) \.\. "\/\.config\/omarchy\/plugins\/(omarchy-keycaps|andrestascon\.keys)\/hypr\/keys\.lua"\)$/
  }
  { lines[NR] = $0; clean[NR] = $0; sub(/\r$/, "", clean[NR]) }
  END {
    inside = 0
    for (i = 1; i <= NR; i++) {
      if (clean[i] == begin) {
        if (inside) exit 2
        inside = 1
      } else if (clean[i] == end) {
        if (!inside) exit 2
        inside = 0
      }
    }
    if (inside) exit 2
    for (i = 1; i <= NR; i++) {
      if (clean[i] == begin) { inside = 1; continue }
      if (clean[i] == end) { inside = 0; continue }
      if (inside) continue
      if ((clean[i] == "-- omarchy-keycaps bridge" || clean[i] == "-- andrestascon.keys bridge") && legacy(clean[i + 1])) continue
      if (legacy(clean[i]) || clean[i] == loader) continue
      printf "%s%s", lines[i], (i < NR || final_newline ? "\n" : "")
    }
  }
' "$HYPRLAND_LUA" > "$TEMP_CONFIG" || {
  echo "Malformed keycaps markers; configuration left unchanged. Fix the BEGIN/END pair first." >&2
  exit 1
}

if [[ "$mode" == install ]]; then
  # A Lua loader needs its own line, even when the existing file has no final LF.
  if [[ -s "$TEMP_CONFIG" && -n "$(tail -c 1 -- "$TEMP_CONFIG")" ]]; then printf '\n' >> "$TEMP_CONFIG"; fi
  printf '%s\n%s\n%s\n' "$BEGIN_MARKER" "$LINE" "$END_MARKER" >> "$TEMP_CONFIG"
fi

if cmp -s -- "$HYPRLAND_LUA" "$TEMP_CONFIG"; then
  if [[ "$mode" == install ]]; then echo "already wired"; else echo "not wired"; fi
  exit 0
fi

BACKUP=$(mktemp "${HYPRLAND_LUA}.bak.XXXXXX")
cp -p -- "$HYPRLAND_LUA" "$BACKUP"
# Preserve the config's permissions and any symlink to a managed dotfile.
cat "$TEMP_CONFIG" > "$HYPRLAND_LUA"
if [[ "$mode" == install ]]; then echo "wired. run: hyprctl reload"; else echo "unwired. run: hyprctl reload"; fi
